### ISSUE TITLE
img

### ISSUE THREAD

**Issue by nastaran-shafiee** [nastaran-shafie/nastaran-shafie#1]
![javascript-plain](https://user-images.githubusercontent.com/115412256/230771578-776eae65-af60-4a80-8696-fde5b70fdb7c.svg)

**Comment by nastaran-shafie** [comment]
![html5-original](https://user-images.githubusercontent.com/115412256/230772374-4bb35c1b-e2f3-4eab-96ef-0fab2ef0061a.svg)

**Comment by nastaran-shafiee** [comment]
![html5-original](https://user-images.githubusercontent.com/115412256/230772430-079b4ba2-031b-4b20-9077-fd60aae44580.svg)

**Comment by nastaran-shafiee** [comment]
![css3-original](https://user-images.githubusercontent.com/115412256/230772472-cb83a261-18e6-40c2-ad69-ff8109073615.svg)

**Comment by nastaran-shafiee** [comment]
![webpack-original](https://user-images.githubusercontent.com/115412256/230772540-478ca422-d3da-41fb-8875-5e2ed4553343.svg)

**Comment by nastaran-shafiee** [comment]
![react-original](https://user-images.githubusercontent.com/115412256/230772612-78e53e57-94a3-42a8-800f-de10ca183b0a.svg)

**Comment by nastaran-shafiee** [comment]
![redux-original](https://user-images.githubusercontent.com/115412256/230772746-883275fe-891e-4dba-bb38-d93c3c42cbe7.svg)

**Comment by nastaran-shafiee** [comment]
![jquery-original-wordmark](https://user-images.githubusercontent.com/115412256/230772812-42a35bef-6feb-40b8-b783-337e6b39a67c.svg)

**Comment by nastaran-shafiee** [comment]
![sass-original](https://user-images.githubusercontent.com/115412256/230772868-0eedb21f-d13c-4b90-a7ac-cfc3f5bf2103.svg)

**Comment by nastaran-shafiee** [comment]
![tailwind](https://user-images.githubusercontent.com/115412256/230772961-24875232-8e74-46c8-9ece-f44d7898e5ac.png)

**Comment by nastaran-shafiee** [comment]
![materialui-original](https://user-images.githubusercontent.com/115412256/230773016-ffe8e7ce-c830-4e33-bd1d-54f9dfd78845.svg)

**Comment by nastaran-shafiee** [comment]
![bootstrap-plain-wordmark](https://user-images.githubusercontent.com/115412256/230773058-9f078eee-db1c-4744-be75-7463741edbfc.svg)

**Comment by nastaran-shafiee** [comment]
![figma-original](https://user-images.githubusercontent.com/115412256/230773125-ff64b468-065e-4501-8375-3b5b4f95a15e.svg)

**Comment by nastaran-shafiee** [comment]
![wordpress](https://user-images.githubusercontent.com/115412256/230773228-653380ae-46a5-43cc-8fc6-a8d4c06f449e.png)

**Comment by nastaran-shafiee** [comment]
![github-original-wordmark](https://user-images.githubusercontent.com/115412256/230773323-2b3df11c-eaf4-42cb-abd7-35554ee4ab26.svg)

**Comment by nastaran-shafiee** [comment]
![telegram](https://user-images.githubusercontent.com/115412256/230774567-78b98a45-4da4-409f-8073-99f4a87b6c01.svg)

**Comment by nastaran-shafiee** [comment]
![whats](https://user-images.githubusercontent.com/115412256/230774988-1897166d-43e3-4af2-82e2-903c460e7c8c.svg)

**Comment by nastaran-shafiee** [comment]
![gmailsvg](https://user-images.githubusercontent.com/115412256/230775297-6d17aebe-f0f7-402b-9d5d-9a796c377357.svg)

**Comment by nastaran-shafiee** [comment]
![welcomePage](https://user-images.githubusercontent.com/115412256/232704583-f0270f04-a910-4086-a7d9-621d75ba3ad6.png)

**Comment by nastaran-shafiee** [comment]
![womanLanding](https://user-images.githubusercontent.com/115412256/232705872-b931f0de-b7c6-4715-92ea-6600f0eb3df1.PNG)

**Comment by nastaran-shafiee** [comment]
![menLanding](https://user-images.githubusercontent.com/115412256/232708578-1f3c4f86-6eee-4ea4-bb81-2d3ab98cf3a9.PNG)

**Comment by nastaran-shafiee** [comment]
![singlePage](https://user-images.githubusercontent.com/115412256/232708870-139a3918-f5ef-4a9b-b567-3face4bf1cf5.png)

**Comment by nastaran-shafiee** [comment]
![singlePage2](https://user-images.githubusercontent.com/115412256/232709161-b9b95f9a-fb48-440b-b72b-a5da89cd504e.png)

**Comment by nastaran-shafiee** [comment]
![cartPage](https://user-images.githubusercontent.com/115412256/232709372-60745e49-62a9-4f59-bb2a-f48d1df6c908.png)

**Comment by nastaran-shafiee** [comment]
![payment](https://user-images.githubusercontent.com/115412256/232709588-f2584339-f22d-4ba3-b85a-f8f670672948.png)

**Comment by nastaran-shafiee** [comment]
![adminLogin](https://user-images.githubusercontent.com/115412256/232709841-8274cbab-64bd-4ca4-aae4-32b722970859.png)

**Comment by nastaran-shafiee** [comment]
![adminProducts](https://user-images.githubusercontent.com/115412256/232710049-1140b27d-6882-49f5-a695-291e968704bc.png)

**Comment by nastaran-shafiee** [comment]
![CategoryPage](https://user-images.githubusercontent.com/115412256/232710263-70fd591c-692e-480e-983f-20adaa6131e9.png)

**Comment by nastaran-shafiee** [comment]
![investory](https://user-images.githubusercontent.com/115412256/232710527-cb2b8b7d-26cc-4e20-bf90-80b1acf8990a.png)

**Comment by nastaran-shafiee** [comment]
![orderlist](https://user-images.githubusercontent.com/115412256/232710702-6cab35c2-72b4-473a-8705-7de38b6df660.png)

**Comment by nastaran-shafiee** [comment]
![setting](https://user-images.githubusercontent.com/115412256/232710965-64c89574-4839-4493-bc39-67365028c066.png)

**Comment by nastaran-shafiee** [comment]
![lightone](https://user-images.githubusercontent.com/115412256/232714794-e93ff72e-41a2-456f-a8bc-3eb3f820311f.PNG)

**Comment by nastaran-shafiee** [comment]
![darkone](https://user-images.githubusercontent.com/115412256/232714980-c8cb57c2-76e1-4bd8-b1d7-ad3b0a72d5eb.png)

**Comment by nastaran-shafiee** [comment]
![Uploading landing1.PNG…]()

**Comment by nastaran-shafiee** [comment]
![landing1](https://user-images.githubusercontent.com/115412256/233838259-49b305c7-fa01-4715-a86a-c34670ee9f6c.PNG)

**Comment by nastaran-shafiee** [comment]
![landing2](https://user-images.githubusercontent.com/115412256/233838353-de0055fc-b23b-4a63-8c2f-cfa5c86eb8ab.PNG)

**Comment by nastaran-shafiee** [comment]
![singl1](https://user-images.githubusercontent.com/115412256/233838393-63d0b4a1-8557-4f7f-915b-72ff1ccd3f01.PNG)

**Comment by nastaran-shafiee** [comment]
![single2PNG](https://user-images.githubusercontent.com/115412256/233838473-b3571705-8fec-4f6b-929e-66ca404ed932.PNG)

**Comment by nastaran-shafiee** [comment]
![login](https://user-images.githubusercontent.com/115412256/233838527-7c67a96d-0360-492d-8d75-04c931e70ac1.png)

**Comment by nastaran-shafiee** [comment]
![cart1](https://user-images.githubusercontent.com/115412256/233838586-ad58951a-afbb-4746-ac2e-358bfa38385f.PNG)

**Comment by nastaran-shafiee** [comment]
![cart2](https://user-images.githubusercontent.com/115412256/233838632-85743a48-c005-4b7d-94d0-4b261a5d6bee.PNG)

**Comment by nastaran-shafiee** [comment]
![Cart3](https://user-images.githubusercontent.com/115412256/233838653-b7a815a9-b237-4318-bdf2-bd909984e1c7.PNG)

**Comment by nastaran-shafiee** [comment]
![paymen1](https://user-images.githubusercontent.com/115412256/233838683-88349f12-552c-4da2-b77a-56a3bc337080.PNG)

**Comment by nastaran-shafiee** [comment]
![payment2PNG](https://user-images.githubusercontent.com/115412256/233838735-8275f6f6-95d5-47f9-ae21-b7395eff5b6a.PNG)

**Comment by nastaran-shafiee** [comment]
![add1](https://user-images.githubusercontent.com/115412256/233838789-bc1789c0-b438-4743-9076-29bbfdb11efc.png)

**Comment by nastaran-shafiee** [comment]
![add2](https://user-images.githubusercontent.com/115412256/233838861-b9a15338-a3d3-4397-a88a-9cdc61461edf.png)
